import re, threading, io
from flask import Flask, request, jsonify, Response
import markdown, yfinance as yf
import engine, ai_research
app = Flask(__name__)
LOCK = threading.Lock()   # engine.META is module-global
MD = lambda t: markdown.markdown(t, extensions=["tables", "fenced_code"])

GLOSS = {
"Revenue": "Total sales from operations. Growth shows demand and market-share gains.",
"Operating Profit (EBITDA)": "Earnings before interest, tax, depreciation and amortisation - core operating profitability.",
"Net Profit (PAT)": "Profit after tax: what is left for shareholders.",
"Cash Flow from Ops (CFO)": "Cash generated by the business itself. Should track PAT over time.",
"Free Cash Flow (FCF)": "CFO minus capex: cash available for dividends, debt reduction or growth.",
"Profit Margin": "PAT / Revenue. How much of each rupee of sales becomes profit.",
"Asset Turnover": "Revenue / Total Assets. How efficiently assets generate sales.",
"Financial Leverage": "Total Assets / Equity. Higher means more debt-funded, boosting ROE and risk.",
"P/E Ratio": "Price / Earnings per share. Years of earnings you pay for. Compare with history and peers.",
"Price / Book (P/B)": "Price / book value per share. Key for banks and asset-heavy firms.",
"EV / EBITDA": "Enterprise value / EBITDA. Debt-neutral valuation, good for comparing capital structures.",
"ROE": "Net profit / equity. Return earned on shareholders' money; >15% is generally strong.",
"ROCE": "EBIT / capital employed. Return on all capital (debt + equity).",
"Debt / Equity": "Total debt / equity. Below 1 is generally comfortable (not for banks).",
"Interest Coverage": "EBIT / interest expense. How many times profits cover interest; >3x is safe.",
"Current Ratio": "Current assets / current liabilities. Short-term liquidity.",
"Cash Conversion Cycle": "Days to turn inventory and receivables into cash, net of payables. Lower is better.",
"FCF / CFO": "Share of operating cash left after capex. High means capital-light.",
"Altman Z-Score": "Bankruptcy-risk model: >2.99 safe, 1.81-2.99 grey, <1.81 distress.",
"Beneish M-Score": "Earnings-manipulation model: above -1.78 is a red flag.",
"20-Day EMA": "Exponential moving average of 20 days - short-term trend.",
"50-Day EMA": "50-day EMA - medium-term trend and common support/resistance.",
"200-Day EMA": "200-day EMA - long-term trend; price above it is a long-term uptrend.",
"RSI (14)": "Momentum oscillator 0-100. >70 overbought, <30 oversold.",
"MACD / Signal": "Trend/momentum from two EMAs; MACD crossing above Signal is bullish.",
"Bollinger (20,2)": "Bands 2 std-dev around the 20-day average; touches show stretched prices.",
"ATR (14)": "Average True Range: typical daily price swing, a volatility gauge.",
"52-Week Range": "Lowest and highest price in the last year.",
"Promoter / Insider Holding": "Share held by promoters/insiders. High and stable shows skin in the game.",
"Institutional Holding (FII + DII)": "Share held by funds, insurers and foreign investors.",
}
def annotate(html):
    def f(m):
        t = m.group(1)
        tip = GLOSS.get(t.strip())
        return m.group(0) if not tip else f'<strong>{t}</strong><span class="i" tabindex="0" data-tip="{tip}">i</span>'
    return re.sub(r"<strong>([^<]{2,40}?):?</strong>", f, html)

def resolve(q):
    q = q.strip()
    if re.fullmatch(r"[A-Za-z0-9&\-]+\.[A-Za-z]{1,3}", q): return q.upper()
    try: qs = [x for x in yf.Search(q, max_results=10).quotes if x.get("quoteType") == "EQUITY"]
    except Exception: qs = []
    if not qs: return q.upper()
    for ex in ("NSI", "BSE"):
        for x in qs:
            if x.get("exchange") == ex: return x["symbol"]
    return qs[0]["symbol"]

@app.get("/api/report")
def report():
    sym = resolve(request.args.get("q", ""))
    peers = [p.strip().upper() for p in request.args.get("peers", "").split(",") if p.strip()]
    try:
        with LOCK:
            md, fig = engine.generate_report(sym, float(request.args.get("wacc", 10)) / 100, float(request.args.get("tg", 4)) / 100, peers, True)
            meta = {k: v for k, v in engine.META.items()}
    except Exception as e:
        return jsonify(error=f"{type(e).__name__}: {e}"), 500
    if fig is None and md.startswith("❌"): return jsonify(error=md), 404
    return jsonify(symbol=sym, html=annotate(MD(md)), meta=meta,
                   chart=fig.to_html(full_html=False, include_plotlyjs="cdn") if fig is not None else "")

@app.get("/api/ai/<section>")
def ai(section):
    if section not in ai_research.P: return jsonify(error="bad section"), 404
    a = request.args
    try:
        txt = ai_research.run(section, name=a.get("name", ""), symbol=a.get("symbol", ""), sector=a.get("sector", ""), industry=a.get("industry", ""), country=a.get("country", ""))
        return jsonify(html=MD(txt))
    except Exception as e:
        return jsonify(error=f"{type(e).__name__}: {e}"), 500

CSS = "body{font-family:Segoe UI,Arial,sans-serif;max-width:960px;margin:24px auto;color:#1a1a1a;font-size:14px}table{border-collapse:collapse;margin:10px 0;width:100%}td,th{border:1px solid #ccc;padding:5px 9px;text-align:left}th{background:#f0f3f7}.i{display:none}pre{background:#f6f8fa;padding:8px}"
@app.post("/download/<fmt>")
def download(fmt):
    body, sym = request.form.get("html", ""), re.sub(r"\W", "_", request.form.get("symbol", "report"))
    doc = f"<html><head><meta charset='utf-8'><style>{CSS}</style></head><body>{body}</body></html>"
    if fmt == "html":
        return Response(doc, mimetype="text/html", headers={"Content-Disposition": f"attachment; filename={sym}_report.html"})
    try:
        from weasyprint import HTML
        return Response(HTML(string=doc).write_pdf(), mimetype="application/pdf", headers={"Content-Disposition": f"attachment; filename={sym}_report.pdf"})
    except Exception:
        return jsonify(error="pdf unavailable"), 501   # front-end falls back to browser print

@app.get("/")
def home(): return Response(open("index.html", encoding="utf-8").read(), mimetype="text/html")

if __name__ == "__main__": app.run(debug=True, port=5000)
